export const Colors = {
  PRIMARY_COLOR: '#5B59FE',
  FADED_PRIMARY_COLOR: '#BCCEFF',
  SECONDARY_COLOR: '#0F0F0F',
  FADED_SECONDARY_COLOR:'#667085',
  WHITE_COLOR: '#FFFFFF',
  BORDER_COLOR: '#D0D5DD',
  FADED_TEXT_COLOR: '#667085',
};